### ISSUE TITLE
Selected item not in view

### ISSUE THREAD

**Issue by qcsltd** [davigmacode/flutter_chips_choice#12]
I have a single horizontal line of chips. The list is long, so the chips scroll off the screen.

If I set the initial value to an item which is off screen e.g. 4, the list still shows item 0 as the first left-most item, and the selected item (4) is not in view. 

Is this behaviour as expected? I would have expected the left most chip to be the selected one.

ChipsChoice<int>.single(
          value: 4,
          padding: const EdgeInsets.fromLTRB(6, 4, 0, 0),
          options: ChipsChoiceOption.listFrom<int, String>(
            source: model.chipItems.map<String>((e) => e.name).toList(),
            value: (i, v) => i,
            label: (i, v) => v,
          ),
          onChanged: (val) {
             setState(() {
                selectedChip = val;
             });
          }
)

**Comment by davigmacode** [comment]
Hi everyone,

I'm sorry to announce that I'm no longer maintaining the [chips_choice](https://pub.dev/packages/chips_choice) package. It's been a great project, but it's become too difficult to maintain.

In its place, I've released a new package called [choice](https://pub.dev/packages/choice). The combination to [smart_select](https://pub.dev/packages/smart_select) and [chips_choice](https://pub.dev/packages/chips_choice) with cleaner, more flexible, and composable API for creating inline or prompted choice widgets with single or multiple selection.

I hope you'll check out [choice](https://pub.dev/packages/choice). I think you'll find it to be a great replacement for [chips_choice](https://pub.dev/packages/chips_choice).

Thanks for your understanding.
