### ISSUE TITLE
choiceLoader: getUsers("element") ????. Why can not use Future Function with parameter. 

### ISSUE THREAD

**Issue by tuemaytinh1981** [davigmacode/flutter_chips_choice#15]
I have code:

Future<List<C2Choice<String>>> getChildHashTags(String element) async {
.....
}

then: 

choiceLoader: getChildHashTags("cat")

=> show error:
The argument type 'Future<List<C2Choice<String>>>' can't be assigned to the parameter type 'Future<List<C2Choice<String>>> Function()'.

Thanks.

**Comment by LAUBENicolas** [comment]
Hi, maybe you could try:

```
choiceLoader: () {
      getChildHashTags("cat");
}
```
So that your principal function isn't async :)
