### ISSUE TITLE
check mark color

### ISSUE THREAD

**Issue by geekhenno** [davigmacode/flutter_chips_choice#16]
hello bro,
How can I change the color of the check mark?

**Comment by davigmacode** [comment]
Currently checkmark color depend on `color` option, but that doesn't stop you from using `choiceBuilder` to create custom chip, here is the [example](https://github.com/davigmacode/flutter_chips_choice/blob/master/example/lib/main.dart#L532)

I hope find a better and flexible way to styling the chip widget
