### ISSUE TITLE
Remove clipBehavior: widget.clipBehavior from widget, breaks in 2+ version

### ISSUE THREAD

**Issue by TinaRanic** [davigmacode/flutter_chips_choice#17]
https://github.com/davigmacode/flutter_chips_choice/blob/master/lib/src/widget.dart

All lines containing clipBehavior: widget.clipBehavior

**Comment by davigmacode** [comment]
Hi everyone,

I'm sorry to announce that I'm no longer maintaining the [chips_choice](https://pub.dev/packages/chips_choice) package. It's been a great project, but it's become too difficult to maintain.

In its place, I've released a new package called [choice](https://pub.dev/packages/choice). The combination to [smart_select](https://pub.dev/packages/smart_select) and [chips_choice](https://pub.dev/packages/chips_choice) with cleaner, more flexible, and composable API for creating inline or prompted choice widgets with single or multiple selection.

I hope you'll check out [choice](https://pub.dev/packages/choice). I think you'll find it to be a great replacement for [chips_choice](https://pub.dev/packages/chips_choice).

Thanks for your understanding.
