### ISSUE TITLE
Null safety for Flutter 2.0

### ISSUE THREAD

**Issue by nipunasudha** [davigmacode/flutter_chips_choice#22]
Could you please update the package for Flutter 2.0 with Null Safety? Thanks

**Comment by viratshukla** [comment]
Yes, please make it null safe

**Comment by ninoorta** [comment]
I'm waiting for it, too . Please update with null safety

**Comment by coastalgit** [comment]
Any ETA on null safety compliance?

**Comment by aemsoftwarearacatuba** [comment]
Please update with null safety

**Comment by davigmacode** [comment]
Fixed in `^2.1.0`
