### ISSUE TITLE
How to Fetch API Data to Multiple Select Chips but Don't Want horizontal Chips

### ISSUE THREAD

**Issue by NavinRiyaz** [davigmacode/flutter_chips_choice#23]
I am using choice chips. how to fetch API data in Works with FormField and Validator Section

Please refer to the image below I want to fetch API Data to the green Rectangle Section.. I don't want a red rectangle model.. How to do it....
![WhatsApp Image 2021-03-20 at 6 24 51 PM](https://user-images.githubusercontent.com/32221786/111870518-4251c480-89ab-11eb-9684-b212ad6de423.jpeg)

**Comment by davigmacode** [comment]
just add `wrapped: true`
you can check the full [example](https://github.com/davigmacode/flutter_chips_choice/blob/master/example/lib/main.dart#L438)
