### ISSUE TITLE
Too bad I spent 2 days just wondering how to customize the chips card. Really disappointed: '(

### ISSUE THREAD

**Issue by hafquangbaox** [davigmacode/flutter_chips_choice#24]

**Comment by davidp918** [comment]
How did you change it? I'm facing this issue too. Please share, thanks

**Comment by basnetjiten** [comment]
style: (index, hello) {
                                return C2ChoiceStyle(
                                    color: const Color(0xff4e4bac)
                                        .withOpacity(0.7));
                              },
                              activeStyle: (index, hello) {
                                return const C2ChoiceStyle(
                                    color: Color(0xff4e4bac));
                              },
                              value: (i, v) => v,
                              label: (i, v) => v,
                            ),
                            choiceStyle: const C2ChoiceStyle(
                                color: Color(0xff18203d),
                                brightness: Brightness.dark),

**Comment by davigmacode** [comment]
If the `choiceStyle` option doesn't met your requirement, you can use choiceBuilder option to create a custom chip widget, here is the [example](https://github.com/davigmacode/flutter_chips_choice/blob/master/example/lib/main.dart#L532)
