### ISSUE TITLE
How to set the initial value

### ISSUE THREAD

**Issue by Small-World** [davigmacode/flutter_chips_choice#28]
Hello, I have a question，How to set the initial value？When I want to create multiple, I select several options by default。
my code is :
ChipsChoice<CharacterEntity>.multiple(
                          value: widget.route._tags,
                          onChanged: (val) {
                            if (val.length < 7) {
                              setState(() {
                                widget.route._tags = val;
                              });
                            }
                          },
                          choiceItems: null,
                          choiceLoader: getChoices,
                          wrapped: true,
                          padding: EdgeInsets.only(top: 10, bottom: 10),
                          spacing: 10,
                          choiceBuilder: (item) {
                            return CustomChip(
                                label: item.label,
                                margin: const EdgeInsets.symmetric(vertical: 5),
                                width: (MediaQuery.of(context).size.width - 20 - 30) / 4,
                                height: 35,
                                selected: item.selected,
                                onSelect: item.select);
                          },
                        ))

**Comment by mage1k99** [comment]
just set the `value` to the desired value to achieve initial value
