### ISSUE TITLE
don't support null safety  sdk: ">=2.12.0 <3.0.0"

### ISSUE THREAD

**Issue by Miladhsp** [davigmacode/flutter_chips_choice#29]
please update it

**Comment by CodingSoot** [comment]
I think this package is dead, which is unfortunate

**Comment by Ebrahimhammad** [comment]
No reply yet, so I guess it is dead.

**Comment by ghadeermohameedelmahdy** [comment]
any update?

**Comment by jbarretojr** [comment]
some parallel package?

**Comment by jheimes-silveira** [comment]
neste repositório você pode usar null-safety

https://github.com/jheimes-silveira/flutter_chips_choice

**Comment by juakotorres** [comment]
@jheimes-silveira thanks it works

**Comment by Miladhsp** [comment]
Thank you for your consideration. 👍🌹
