### ISSUE TITLE
Background color

### ISSUE THREAD

**Issue by erf** [davigmacode/flutter_chips_choice#3]
Is there a easy way to set background color for chips?

They always seem to be white now.

**Comment by davigmacode** [comment]
try this configuration
```
ChipsChoice.single/multiple(
  ...,
  ...,
  itemConfig: ChipsChoiceItemConfig(
    selectedColor: Colors.green,
    unselectedColor: Colors.blueGrey,
    selectedBrightness: Brightness.dark,
    unselectedBrightness: Brightness.dark,
  ),
);
```
the selected background will be `Colors.green` and the unselected background will be `Colors.blueGrey` while the label color will be `Colors.white`, you can set them both or only one of them.

if this behavior doesn't meet your need, you still can use [`itemBuilder`](https://pub.dev/documentation/chips_choice/latest/chips_choice/ChipsChoice/itemBuilder.html) to create custom chip, see the [example here](https://github.com/davigmacode/flutter_chips_choice/blob/master/example/lib/main.dart#L288)

**Comment by erf** [comment]
Thanks, but can you have a green background and black text?

**Comment by davigmacode** [comment]
Sorry, you need to create a custom chip to achieve that
