### ISSUE TITLE
implement with model class 

### ISSUE THREAD

**Issue by YouSour** [davigmacode/flutter_chips_choice#39]
hi, cloud you give me an example how to implement with model class ?

my model class :
```
import 'package:flutter/material.dart';
import 'package:json_annotation/json_annotation.dart';
import '../utils/icon_model_converter.dart';
part 'option_model.g.dart';

@JsonSerializable()
class OptionModel {
  @JsonKey(
      disallowNullValue: true,
      fromJson: IconModelConverter.fromJson,
      toJson: IconModelConverter.toJson)
  final IconData? icon;
  final String label;
  late dynamic value;


  OptionModel(
      {this.icon,
      required this.label,
      required this.value
});

  factory OptionModel.fromJson(Map<String, dynamic> json) =>
      _$OptionModelFromJson(json);
  Map<String, dynamic> toJson() => _$OptionModelToJson(this);
}

```

**Comment by DaZealous** [comment]
@YouSour , did you get any solution on this ?

**Comment by davigmacode** [comment]
Hi everyone,

I'm sorry to announce that I'm no longer maintaining the [chips_choice](https://pub.dev/packages/chips_choice) package. It's been a great project, but it's become too difficult to maintain.

In its place, I've released a new package called [choice](https://pub.dev/packages/choice). The combination to [smart_select](https://pub.dev/packages/smart_select) and [chips_choice](https://pub.dev/packages/chips_choice) with cleaner, more flexible, and composable API for creating inline or prompted choice widgets with single or multiple selection.

I hope you'll check out [choice](https://pub.dev/packages/choice). I think you'll find it to be a great replacement for [chips_choice](https://pub.dev/packages/chips_choice).

Thanks for your understanding.
