### ISSUE TITLE
Minimum chip width

### ISSUE THREAD

**Issue by erf** [davigmacode/flutter_chips_choice#4]
I would like to set a minimum chip width, if label is short.

**Comment by davigmacode** [comment]
Unfortunately, currently there is no easy way to achieve that. You need to create a custom chip using the [`itemBuilder`](https://pub.dev/documentation/chips_choice/latest/chips_choice/ChipsChoice/itemBuilder.html) configuration, please see the [example here](https://github.com/davigmacode/flutter_chips_choice/blob/master/example/lib/main.dart#L288)
