### ISSUE TITLE
No scroll on desktop build

### ISSUE THREAD

**Issue by valientegaston** [davigmacode/flutter_chips_choice#41]
Hello! excellent widget! Thank you very much for creating and maintaining it. I just tried the latest version without problems on IOS, but on MacOS I can't get to move the chips horizontally by dragging with the mouse. The code is the first one you have published in the readme, called 'Simple usage'. 

Thank you.

**Comment by davigmacode** [comment]
Hi everyone,

I'm sorry to announce that I'm no longer maintaining the [chips_choice](https://pub.dev/packages/chips_choice) package. It's been a great project, but it's become too difficult to maintain.

In its place, I've released a new package called [choice](https://pub.dev/packages/choice). The combination to [smart_select](https://pub.dev/packages/smart_select) and [chips_choice](https://pub.dev/packages/chips_choice) with cleaner, more flexible, and composable API for creating inline or prompted choice widgets with single or multiple selection.

I hope you'll check out [choice](https://pub.dev/packages/choice). I think you'll find it to be a great replacement for [chips_choice](https://pub.dev/packages/chips_choice).

Thanks for your understanding.
