### ISSUE TITLE
Validation

### ISSUE THREAD

**Issue by yalva** [davigmacode/flutter_chips_choice#5]
How to validate the choice, ex: at least one choice selected or should display error message?

**Comment by davigmacode** [comment]
You can combine with [FormField](https://api.flutter.dev/flutter/widgets/FormField-class.html), please follow these [example](https://github.com/davigmacode/flutter_chips_choice/blob/master/example/lib/main.dart#L228)

**Comment by uzairahmed97** [comment]
How to change shape or border-radius of chip?

**Comment by deandreamatias** [comment]
Can close this issue I guess.
What do you think @yalva @davigmacode ?

**Comment by davigmacode** [comment]
> How to change shape or border-radius of chip?

Hi @uzairahmed97.
Please check at these [example](https://github.com/davigmacode/flutter_chips_choice/blob/e9bc9a8f2c037f454fcd09049f16513a14e1a777/example/lib/main.dart#L176), I just updated it.

> Can close this issue I guess.
> What do you think @yalva @davigmacode ?

Sure, thanks @deandreamatias
