### ISSUE TITLE
Theme colours

### ISSUE THREAD

**Issue by shptecheu** [davigmacode/flutter_chips_choice#6]
Anyone tried using this with a custom theme? Is there any easy way for the chips to reflect colours of the custom theme being used?

**Comment by davigmacode** [comment]
Refer to the source code at lines [119](https://github.com/davigmacode/flutter_chips_choice/blob/master/lib/chips_choice.dart#L119) and [120](https://github.com/davigmacode/flutter_chips_choice/blob/master/lib/chips_choice.dart#L120).

You can set explicitly for each `ChipsChoice` widget
```
ChipsChoice<String>.single(
  value: ...,
  options: ...,
  onChanged: ...,
  itemConfig: ChipsChoiceItemConfig(
    selectedColor: Colors.green,
    unselectedColor: Colors.blueGrey,
  ),
);
```

or set once for all `ChipsChoice` widget
```
MaterialApp(
  theme: ThemeData(
    primaryColor: Colors.green,
    unselectedWidgetColor: Colors.blueGrey,
  ),
  body: Scaffold(
    body: Column(
      children: <Widget>[
        ChipsChoice<String>.single(
          value: ...,
          options: ...,
          onChanged: ...,
        ),
        ChipsChoice<String>.single(
          value: ...,
          options: ...,
          onChanged: ...,
        ),
      ],
    ),
  ),
);
```

**Comment by shptecheu** [comment]
Thanks for this, it was a step in the right direction. I was doing this right in my code, and it was working for a light theme, but not for a dark theme. It seems to be quirk in the material dark theme, so not related to this package.
