### ISSUE TITLE
Error when setting margin

### ISSUE THREAD

**Issue by dr0-dev** [davigmacode/flutter_chips_choice#9]
I get the error:

type 'EdgeInsets' is not a subtype of type 'bool'

if I set a margin like this:            `margin: EdgeInsets.all(10)`

the problem is found here:

`      padding: config.margin ?? isWrapped ? const EdgeInsets.all(0) : const EdgeInsets.all(5)`

**Comment by davigmacode** [comment]
Hi @dromedian 
Please upgrade to the latest 1.4.1 version.

Thanks to @noliran who fixes the bug
